defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: simple_objective
    storage: null
    n_trials: 100
    n_jobs: 1

    params:
      parameters_.main_model_drop_out_p: range(0.1, 0.7, 0.05)
      parameters_.image_encoder_drop_out_p: range(0.1, 0.7, 0.05)
      parameters_.image_token_size: range(12, 32, 1)
      parameters_.batch_size: range(1, 9, 1)
      parameters_.lr: range(0.00001, 0.00005, 0.00001)
      parameters_.weight_decay: choice(0.001, 0.01, 0.002,0.003,0.004,0.005 )


parameters_:
  batch_size: 5
  lr: 0.00002
  image_token_size: 17
  main_model_drop_out_p: 0.5
  image_encoder_drop_out_p: 0.15
  weight_decay: 0.01
  argument_text_data: True
  argument_text_rank: -37
  

env_:
  image_size: 224
  # image_size: 512
  epochs: 12
  gpus: 2
  num_worker: 4
  train_data_rate: 0.9
  data_save_dir: "./data_save_temp"
  # train_path: "/data/mrjaehong/handwriting_gen/today_study/대회/dacon/관광데이터/train_sample.csv"
  train_path: "/data/mrjaehong/handwriting_gen/today_study/대회/dacon/관광데이터/train.csv"
  test_path: "/data/mrjaehong/handwriting_gen/today_study/대회/dacon/관광데이터/test2.csv"
  k_fold_n: 5
  experiments_id: 0
  








