defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: simple_objective
    storage: null
    n_trials: 100
    n_jobs: 1

    params:
      parameters_.main_model_drop_out_p: range(0.1, 0.7, 0.05)
      parameters_.image_encoder_drop_out_p: range(0.1, 0.7, 0.05)
      parameters_.image_token_size: range(12, 32, 1)
      parameters_.batch_size: range(1, 9, 1)
      parameters_.lr: range(0.00001, 0.00005, 0.00001)

parameters_:
  batch_size: 5
  lr: 0.00002
  image_token_size: 17
  main_model_drop_out_p: 0.4
  image_encoder_drop_out_p: 0.15
  
env_:
  image_size: 224
  # image_size: 512
  epochs: 12
  gpus: 2
  num_worker: 4
  train_data_rate: 0.9
  # train_path: "/data/mrjaehong/handwriting_gen/today_study/대회/dacon/관광데이터/train_sample_startifedkfold.csv"
  train_path: "/data/mrjaehong/handwriting_gen/today_study/대회/dacon/관광데이터/train.csv"
  test_path: "/data/mrjaehong/handwriting_gen/today_study/대회/dacon/관광데이터/test.csv"
  k_fold_n: 5
  experiments_id: 0
  








