defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: simple_objective
    storage: null
    n_trials: 20
    n_jobs: 1

    params:
      main_model_drop_out_p: range(0, 0.5, 0.05)
      image_encoder_drop_out_p: range(0, 0.5, 0.05)
      # resnet_choice: int(tag(log, interval(1, 32)))
      resnet_choice: choice(0, 1, 2)
      image_token_size: range(3, 16, 1)

base_main_model_name: kobert
batch_size: 6
image_size: 224
epochs: 2
num_worker: 4
lr: 0.00002
gpus: 2
train_data_rate: 0.9
train_path: "/data/mrjaehong/handwriting_gen/today_study/대회/dacon/관광데이터/train_sample.csv"
test_path: "/data/mrjaehong/handwriting_gen/today_study/대회/dacon/관광데이터/test.csv"
main_model_drop_out_p: 0.3
image_encoder_drop_out_p: 0.3
image_token_size: 3
resnet_choice: 0








